### ISSUE TITLE
Kint_Renderer_Rich

### ISSUE THREAD

**Issue by MouhamedAymen** [rtconner/laravel-kint#15]
It throws an error when trying to start the server:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Conner\Kint\Kint_Renderer_Rich' not found
```
It seems that you forgot to import the Kint_Renderer_Rich Class in KintServiceProvider.php

**Comment by d1c1pl3** [comment]
Confirmed

**Comment by vesper8** [comment]
same problem

```
"Class 'Conner\Kint\Kint_Renderer_Rich' not found"
```

simply adding `use Kint_Renderer_Rich;` at the top of the KintServiceProvider makes the problem go away

**Comment by rtconner** [comment]
Sorry everyone. Resolved.
