### ISSUE TITLE
Installation dies due to function re-declaration.

### ISSUE THREAD

**Issue by Orteko** [rtconner/laravel-kint#2]
On a new install with laravel 5 using the composer install string in the readme (composer require rtconner/laravel-kint "~1.0"), the installation fails with the following error:

```
Using version ^1.1 for rtconner/laravel-kint
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing rtconner/laravel-kint (1.1.0)
    Loading from cache

Writing lock file
Generating autoload files
PHP Fatal error:  Cannot redeclare ddd() ...
```

This looks like it is caused by a simple typo in laravel-kint.php:

```
if(!defined('ddd')) {
```

where defined should probably be replaced with function_exists as defined only applies to constants:

```
if(!function_exists('ddd')) {
```

**Comment by longestdrive** [comment]
I have the same issue, changed to function_exists as above and now working

**Comment by odin88** [comment]
+1

**Comment by rtconner** [comment]
Oh forgot to close this. It was fixed about 2 weeks ago.
